#设置端口及访问路径
server:
  port: 7529
  servlet:
    context-path: /api

spring:
#  唯一标识，注册中心需要使用，用于区分
  application:
    name: rxapi-backend
#  mysql数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ruoxiapi
    username: zhourx
    password: zhouruxin
#  路径匹配规则
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # session 一天过期
  session:
    timeout: 86400
    store-type: none
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #开启
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1
      logic-not-delete-value: 0
#自定义sdk配置
rxapi:
  client:
    access-key: 6329e9f3481967f6f8ba885fd0581f26
    secret-key: 9d2953d211dfff9bb5adac8c013093e3

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848


